### ISSUE TITLE
Does not work with docker-compose files version 2

### ISSUE THREAD

**Issue by git-commit** [herzog31/docker-deploy-bamboo-go#1]
I've tried using this script with newer docker-compose.yml's that have `version: '2'` and it crashes.

**Comment by herzog31** [comment]
Can you please provide a more specific description of what is not working? Are there any error logs of the script?

**Comment by git-commit** [comment]
Sorry, looks like the build machine itself was using a non updated version of docker-compose. Your script works as intended
